name: CI-pipeline
on:
  push:
    branches:
      - master
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: exif

      - name: Install dependencies
        run: composer update --ignore-platform-req=php --no-interaction --no-progress

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          mode: build

      - name: Build the docker-compose stack
        run: |
          docker-compose build
          docker-compose up -d
          docker ps -a

      - name: Test
        run: php ./vendor/bin/pest
        
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy
        uses: docker/build-push-action@v3
        with:
          push: true
          target: alexpdv/projet_dev_ops
          tags: latest
          dockerfile: Dockerfile
