name: CI-pipeline
on:
  push:
    branches:
      - master
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: exif

      - name: Install dependencies
        run: composer update --ignore-platform-req=php --no-interaction --no-progress

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          mode: production

      - name: Some other action
        run: |
          echo "Variable 1: ${{ env.DB_PORT }}"
          echo "Variable 2: ${{ env.DB_PORT }}"

      - name: Build
        run: echo "build..."

      - name: Test
        run: php ./vendor/bin/pest

      - name: Deploy
        run: echo "deploy..."
