name: CI-pipeline
on:
  push:
    branches:
      - master
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: echo "install..."
        uses: shivammathur/setup-php@v2
        with:
        php-version: '8.0'
        extensions: exif
        run: composer update --ignore-platform-req=php --no-interaction --no-progress

      - name: Build
        run: echo "build..."

      - name: Test
        run: echo "test..."
        run: php ./vendor/bin/pest

      - name: Deploy
        run: echo "deploy..."
